name: Build ISO
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
       GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
    container:
      image: registry.getcryst.al/crystal/misc/docker:latest
      options: --privileged

    steps:
      - name: Prepare
        id: fieldPrep
        run: |
          # Ensure container is up to date and has necessary packages
            pacman -Syu --needed --noconfirm
            pacman -S git pacman-contrib archiso bind --needed --noconfirm

          # Ensure repo.getcryst.al is up
            nslookup repo.getcryst.al       
            
          # Set ${BUILD_DATE} and push it to GitHub as an env variable
          # ISO-8601 Format
            export BUILD_DATE=$(date +'%Y-%m-%d')
            echo export BUILD_DATE=$(date +'%Y-%m-%d') >> $GITHUB_ENV

          # Clone ISO repo
            git clone https://git.getcryst.al/crystal/misc/iso
            
      - name: Build
        id: build
        run: |
          # Jump into ISO repo, build ISO and rename to match BUILD_DATE
            cd iso
            bash ./build.sh --build-iso
            if [[ ! "$(ls *.iso)" == "crystal-live-${BUILD_DATE}-x86_64.iso" ]]; then
              mv *.iso crystal-live-${BUILD_DATE}-x86_64.iso
            fi
            md5sum *.iso > MD5SUM-iso
            
          # Remove chrooted.sh between operations
            rm chrooted.sh

          # Likewise, but for the rootfs
            bash ./build.sh --build-bootstrap
            mv *.tar.gz crystal-rootfs-${BUILD_DATE}-x86_64.tar.gz
            md5sum *.tar.gz > MD5SUM-rootfs

          # Remove chrooted.sh one final time
            rm chrooted.sh

      - name: Get tag name from date
        id: makeTag
        if: ${{ steps.check_tag.outputs.exists == 'false' }}
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ env.BUILD_DATE }}
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            iso/*.iso
            iso/*.tar.gz
            iso/MD5SUM*
          tag_name: ${{ env.BUILD_DATE }}
          generate_release_notes: true
