name: Build ISO
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
       GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
    container:
      image: registry.getcryst.al/crystal/misc/docker:latest
      options: --privileged

    steps:
      - name: Prepare
        id: fieldprep
        run: |
          # Ensure container is up to date and has necessary packages
            pacman -Syu --needed --noconfirm
            pacman -S git pacman-contrib archiso bind --needed --noconfirm

          # Ensure repo.getcryst.al is up
            nslookup repo.getcryst.al       
            
          # Set ${BUILD_DATE}
          # ISO-8601 Format
            export BUILD_DATE=$(date +'%Y-%m-%d')

          # Clone ISO repo
            git clone https://git.getcryst.al/crystal/misc/iso
            
      - name: Build
        id: build
        run: |
          # Jump into ISO repo, build ISO and rename to match BUILD_DATE
            cd iso
            bash ./build.sh --build-iso
            if [[ ! "$(ls *.iso)" == "crystal-live-${BUILD_DATE}-x86_64.iso" ]]; then
              mv *.iso crystal-live-${BUILD_DATE}-x86_64.iso
            fi
            md5sum *.iso > MD5SUM-iso
            
          # Remove chrooted.sh between operations
            rm chrooted.sh

          # Likewise, but for the rootfs
            bash ./build.sh --build-bootstrap
            mv *.tar.gz crystal-rootfs-${BUILD_DATE}-x86_64.tar.gz
            md5sum *.tar.gz > MD5SUM-rootfs

          # Remove chrooted.sh one final time
            rm chrooted.sh

      - name: Upload and Create Release
        id: fullsend
        uses: actions/create-release@latest
        with:
          tag_name: ${{ env.BUILD_DATE }}
          release_name: ${{ env.BUILD_DATE }}

    
           
